#cl_stlfilt = '"C:\Documents and Settings\peter\STLFilt\CL.exe"'
toolset = 'gcc'
gcc_stlfilt = 'gfilt /hdr:L /cand:L'
#win32_boostdir = 'C:\\Users\\peter\\Documents\\Code\\boost_1_36_0';
win32_lokidir = 'C:\\Users\\peter\\Documents\\Code\\loki-0.1.6';
win32_ccpdir = 'C:\\Program Files\\Microsoft Compute Cluster Pack';
QTDIR = 'C:\\Users\\peter\\Documents\\Code\\qt-win-opensource-src-4.4.3';
use_ati_brook=0;
BROOKROOT = '/usr/local/atibrook'
