cl_stlfilt = '"..\\stlfilt\\mfilt.bat"'
#cl_stlfilt = "icl"
#toolset = 'gcc'
#gcc_stlfilt = 'gfilt'
#win32_boostdir = 'C:\\Users\\peter\\Documents\\Code\\boost_1_36_0';
win32_lokidir = 'C:\\Users\\peter\\Documents\\Code\\loki-0.1.7';
win32_tbbdir = 'C:\\Users\\peter\\Documents\\Code\\tbb22_20090809oss';
win32_bsponmpidir = 'C:\\Users\\peter\\workspace\\bsponmpi'
win32_bsp_cppdir = 'C:\\Users\\peter\\workspace\\bsp_cpp'
use_ati_brook = 0; # does not work on Win64 yet
BROOKROOT='C:\\Program Files (x86)\\ATI\\ATI Brook+ 1.4.0_beta'
configure = 1;
additional_lflags = '/LARGEADDRESSAWARE:NO /LIBPATH:libs/asmlib alibcof64.lib'
#additional_cflags = '/D_USE_ASMLIB /Ob2'
sequential=1