#toolset='icc'
win32_boostdir = 'c:\\Boost\\include';
win32_lokidir = 'c:\\Boost\\loki';
win32_tbbdir = 'C:\\Users\\peter\\Documents\\Code\\tbb30_018oss';
win32_bsponmpidir = 'C:\\Users\\peter\\workspace\\bsponmpi'
use_ati_brook = 0;
BROOKROOT='C:\\Program Files\\ATI\\ATI Brook+ 1.4.0_beta'
configure = 1
sequential=1
debuginfo = 1
additional_lflags = "/LTCG /LARGEADDRESSAWARE:NO"