Import('root')

# environment for creating reference builds 
refenv = root.Clone()
refenv.Append(CCFLAGS = "-DTEST_REFERENCE")

# This one tests the MachineWordVector class.
root.Program('#bin/mwwtesting', ['mwwtesting.cpp'])

# Test of all LCS computation routines.
root.Program('#bin/lcstesting', ['lcstesting.cpp'])

# Test generic dynamic programming framework
root.Program('#bin/dynamicprogramming_testing', ['dynamicprogramming_testing.cpp'])


# Test window local comparison routines
root.Program('#bin/windowlocaltesting', ['windowlocaltesting.cpp'])

# compare performance of window-local comparison algorithms
root.Program('#bin/windowlocalcomparison', ['windowlocalcomparison.cpp'])

# test range tree code
root.Program('#bin/rangetesting', ['rangetesting.cpp'])
root.Program('#bin/rangecomparison', ['rangecomparison.cpp'])
root.Program('#bin/rangecomparison2d', ['rangecomparison2d.cpp'])

# test seaweed code
root.Program('#bin/seaweedtesting', ['seaweedtesting.cpp'])
Command("seaweedtesting_reference.cpp", "seaweedtesting.cpp", Copy("$TARGET", "$SOURCE"))

refenv.Program('#bin/seaweedtesting_reference', ['seaweedtesting_reference.cpp'])

# test the GPU code
if root['use_ati_brook']:
	root.Program('#bin/gpulibtesting', ['gpulibtesting.cpp'])