
Import("root")
Import("mpi")

# serial/multi-core code
#root.Program('#bin/WindowAlignment', 'WindowAlignment.cpp')
root.Program('#bin/PostprocessWindows', 'PostprocessWindows.cpp')

# MPI code
mpi.Program('#bin/WindowAlignment_BSP', 'WindowAlignment_BSP.cpp')
